theme: jekyll-theme-architect
title: Parallel Rubiks Cube Solver
description: Parallel Rubiks Cube Solver implementation using OpenMP for the 15-418 class. Developed by Diego Garza Rodriguez and Nihar Pol. Fall 2017
